import { Box } from "@chakra-ui/react";
import Head from "next/head";
import css from "../styles/home.module.css"

export default function Home() {

  
  return (
    <>
        <Head>
          <title>Home Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
 
    </>
  );
}
